[tool.poetry]
name = "onlysubs"
version = "0.1.0"
description = ""
authors = ["lLotosl <lotosyt1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.101.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
